### ISSUE TITLE
Code doesn't recognise time of day

### ISSUE THREAD

**Issue by VinceAdult** [pipwerks/OS-X-Wallpaper-Changer#10]
I tried having GeekTool refresh the command every second and all of a sudden the wallpaper is changing every second. Shouldn't it refresh the command, realise that it's a specific time of day and display that specific wallpaper in the corresponding folder? I don't see how changing the refresh rate to 1800 seconds as advised will change this, then the wallpaper will just refresh every 15 minutes, making it no different than Apple's default 'change background' time interval.

This is the same if I just play the code myself. Every time I run the code, the background changes. It doesn't matter what time of day it is.

**Comment by pipwerks** [comment]
Hi Vince

I haven't used this code for years, and can't vouch for its current state. This code was written 8 years ago; it's simple enough that it should still work (AppleScript is still fully supported by macOS), but I can't say whether any part of it is obsolete.

Now that macOS have native dynamic wallpapers, I suggest using theirs. Here's a good article on how to cycle wallpapers hourly with no scripting required. https://appleinsider.com/articles/18/10/01/how-to-create-your-own-dynamic-desktops-in-macos-mojave
