### ISSUE TITLE
Script periodOfDay Logic

### ISSUE THREAD

**Issue by jonpa89** [pipwerks/OS-X-Wallpaper-Changer#5]
Was having an issue 9:00pm-11:59pm section of the script; the last line: 

else if (h ≥ 21 or h < 8) then
    set periodOfDay to eveningLate

was overriding the morningEarly default logic, such that 12:00am-7:59am were registering as eveningLate.  I just removed ' or h < 8' and seems to be functioning properly now.

thanks again for sharing.

**Comment by pipwerks** [comment]
I recall this change conflicts with something someone else reported. Will have to look into it. Thanks

**Comment by pipwerks** [comment]
This script is no longer maintained, closing.
