### ISSUE TITLE
Not changing wallpaper

### ISSUE THREAD

**Issue by CalebKierum** [pipwerks/OS-X-Wallpaper-Changer#7]
Causes my wallpaper to go to a plain blue color. I have even tried this with the default images. I have confirmed that the file paths are correct using terminal.

**Comment by dvorakjcom** [comment]
Hello. I had a problem, that my wallpaper to go to a default Sierra wallpaper. Then I tried to turn off the option "Change picture Every day" at "Desktop & Screensaver" in "System Settings", and now it works.

**Comment by sh78** [comment]
I just tried this on macOS 10.13.5. The apple script will only change the wallpaper if I check **and then uncheck** the preference mentioned above by @dvorakjcom. Doing this makes it work once, and then I have to check/uncheck the preference again.

**Comment by pipwerks** [comment]
This script is no longer maintained, and is superseded by new macOS native functionality. Closing ticket.
