### ISSUE TITLE
All desktops not updating

### ISSUE THREAD

**Issue by karanjot21** [pipwerks/OS-X-Wallpaper-Changer#9]
If you are working on multiple desktops, only the current desktop wallpaper gets updated. Other desktops still show the previous wallpaper only.
Note that I am using the single built-in monitor in the MacBook with no external displays attached.

**Comment by karanjot21** [comment]
```
set theDesktops to a reference to every desktop
log (count theDesktops)
```
logs `(*1*)` even when multiple desktops are there

**Comment by karanjot21** [comment]
Never mind, searching online regarding the issue, got to know that there's no way to detect the number of spaces (desktops) open

**Comment by pipwerks** [comment]
Sorry. FYI macOS Mojave supports dynamic desktop wallpapers. This script may not be needed much longer. https://mashable.com/article/more-dynamic-desktop-wallpapers-mojave/#MmQ_ERbUzsqa
